# Host-side end-to-end test for the interactive `nix run` installer.
#
# The runner deliberately starts the installer with an empty home, scrubbed
# environment, and unusable inherited PATH. The app's Nix closure must supply
# every executable it needs. Unlike a normal Nix build sandbox, the runner is
# executed with `nix run` so nested Nix and Home Manager operations can reach
# the host daemon.
{ pkgs, self, home-manager, nixpkgs, nix-index-database }:

let
  system = pkgs.stdenv.hostPlatform.system;
  installerProgram = self.apps.${system}.default.program;
  chshStub = pkgs.writeShellScript "dotfiles-test-chsh" ''
    printf '%s\n' "$*" > "$DOTFILES_TEST_CHSH_LOG"
  '';
in
pkgs.writeShellApplication {
  name = "dotfiles-installer-bootstrap-test";
  runtimeInputs = [
    pkgs.coreutils
    pkgs.gnugrep
    pkgs.nix
  ];
  text = ''
    with_sudo=false
    if [[ ''${1:-} == --with-sudo ]]; then
      with_sudo=true
      shift
    fi
    if (($#)); then
      printf 'Usage: dotfiles-installer-bootstrap-test [--with-sudo]\n' >&2
      exit 2
    fi

    test_home=$(mktemp -d "''${TMPDIR:-/tmp}/dotfiles-installer-test.XXXXXX")
    chmod 700 "$test_home"
    mkdir -m 700 "$test_home/runtime" "$test_home/tmp"

    cleanup() {
      status=$?
      if ((status != 0)) || [[ ''${KEEP_DOTFILES_TEST_HOME:-0} == 1 ]]; then
        printf 'Installer test home retained at %s\n' "$test_home" >&2
      elif [[ -n $test_home && -d $test_home && $test_home != / ]]; then
        chmod -R u+w "$test_home" 2>/dev/null || true
        rm -rf -- "$test_home"
      fi
      exit "$status"
    }
    trap cleanup EXIT

    fail() {
      printf 'FAIL: %s\n' "$*" >&2
      exit 1
    }

    assert_file_contains() {
      local path=$1
      local expected=$2
      [[ -f $path ]] || fail "expected a file at $path"
      grep -Fqx -- "$expected" "$path" ||
        fail "expected $path to contain: $expected"
    }

    run_installer() {
      env -i \
        HOME="$test_home" \
        USER="$(id -un)" \
        LOGNAME="$(id -un)" \
        PATH=/path-that-does-not-exist \
        TMPDIR="$test_home/tmp" \
        XDG_CACHE_HOME="$test_home/.cache" \
        XDG_CONFIG_HOME="$test_home/.config" \
        XDG_DATA_HOME="$test_home/.local/share" \
        XDG_RUNTIME_DIR="$test_home/runtime" \
        XDG_STATE_HOME="$test_home/.local/state" \
        DOTFILES_USER="$(id -un)" \
        DOTFILES_HOME="$test_home" \
        DOTFILES_STATE_VERSION=25.11 \
        DOTFILES_FORCE_LOGIN_SHELL_SETUP="''${DOTFILES_FORCE_LOGIN_SHELL_SETUP:-0}" \
        DOTFILES_URL="path:${self}" \
        DOTFILES_NIXPKGS_URL="path:${nixpkgs}" \
        DOTFILES_HOME_MANAGER_URL="path:${home-manager}" \
        NIX_SSL_CERT_FILE="${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt" \
        NIX_USER_CONF_FILES=/dev/null \
        NIX_CONFIG=$'experimental-features = nix-command flakes\nflake-registry =\n' \
        ${pkgs.nix}/bin/nix run "path:${self}" -- "$@"
    }

    # Keep every locked source in the runner closure, including the nested
    # nix-index-database input that the generated consumer flake inherits.
    [[ -e ${nix-index-database} ]]

    printf 'Testing installer in empty home %s\n' "$test_home"

    if output=$(run_installer init 2>&1); then
      fail "legacy init command unexpectedly succeeded"
    fi
    [[ $output == *"replaced by the interactive installer"* ]] ||
      fail "legacy init command did not explain its replacement"

    if output=$(run_installer </dev/null 2>&1); then
      fail "interactive installer unexpectedly ran without a terminal"
    fi
    [[ $output == *"interactive installer needs a terminal"* && $output == *"--unattended"* ]] ||
      fail "non-terminal error did not suggest --unattended"

    run_installer --unattended

    flake_path="$test_home/.config/home-manager/flake.nix"
    nix_conf="$test_home/.config/nix/nix.conf"
    assert_file_contains "$flake_path" '# Generated by TheFurnace/dotfiles installer.'
    grep -Fq 'system        = "${system}";' "$flake_path" ||
      fail "generated Home Manager flake has the wrong platform"
    assert_file_contains "$nix_conf" 'experimental-features = nix-command flakes'

    printf '%s\n' \
      'substituters = https://cache.nixos.org' \
      'experimental-features = nix-command' > "$nix_conf"
    run_installer --unattended
    assert_file_contains "$nix_conf" 'substituters = https://cache.nixos.org'
    assert_file_contains "$nix_conf" 'experimental-features = nix-command flakes'
    [[ $(grep -c '^experimental-features = ' "$nix_conf") == 1 ]] ||
      fail "installer left duplicate experimental-features settings"

    profile="$test_home/.local/state/nix/profiles/home-manager"
    gcroot="$test_home/.local/state/home-manager/gcroots/current-home"
    [[ -e $profile ]] || fail "Home Manager profile was not activated"
    [[ -L $gcroot ]] || fail "Home Manager current-home gcroot is missing"

    [[ -e $test_home/.config/fish/config.fish ]] || fail "Fish config is missing"
    for path in \
      "$test_home/.config/git/config" \
      "$test_home/.config/nvim/init.lua" \
      "$test_home/.config/kitty/kitty.conf" \
      "$test_home/.config/oh-my-posh/themes/lambda.omp.json"
    do
      [[ -L $path ]] || fail "expected managed symlink at $path"
    done

    for program in jq rg dotfiles-ai; do
      [[ -x $test_home/.nix-profile/bin/$program ]] ||
        fail "$program is missing from the activated profile"
    done

    first_generation=$(readlink "$gcroot")
    run_installer --unattended
    second_generation=$(readlink "$gcroot")
    [[ $first_generation == "$second_generation" ]] ||
      fail "current-home gcroot changed across idempotent runs"

    output=$(DOTFILES_FORCE_LOGIN_SHELL_SETUP=1 run_installer --unattended)
    [[ $output == *"setup-shell fish"* ]] ||
      fail "generic-Linux activation did not print the login-shell hint"

    if [[ $(id -u) -ne 0 ]]; then
      if output=$(run_installer setup-shell fish 2>&1); then
        fail "setup-shell unexpectedly succeeded without root"
      fi
      [[ $output == *"must be run with sudo"* && $output == *"setup-shell fish"* ]] ||
        fail "setup-shell root refusal did not include the expected guidance"
    fi

    if run_installer setup-shell zsh >/dev/null 2>&1; then
      fail "setup-shell accepted an unsupported shell"
    fi

    if $with_sudo; then
      sudo_program="''${DOTFILES_TEST_SUDO:-/usr/bin/sudo}"
      [[ -x $sudo_program ]] || fail "--with-sudo requested but $sudo_program is unavailable"
      shells_file="$test_home/test-shells"
      chsh_log="$test_home/test-chsh.log"
      printf '/bin/sh\n' > "$shells_file"

      "$sudo_program" -n ${pkgs.coreutils}/bin/env -i \
        PATH=/path-that-does-not-exist \
        DOTFILES_USER="$(id -un)" \
        DOTFILES_HOME="$test_home" \
        DOTFILES_CHSH="${chshStub}" \
        DOTFILES_TEST_CHSH_LOG="$chsh_log" \
        DOTFILES_SHELLS_FILE="$shells_file" \
        DOTFILES_URL="path:${self}" \
        ${installerProgram} setup-shell fish

      assert_file_contains "$shells_file" "$test_home/.nix-profile/bin/fish"
      assert_file_contains "$chsh_log" "-s $test_home/.nix-profile/bin/fish $(id -un)"
      [[ $(grep -c -Fx "$test_home/.nix-profile/bin/fish" "$shells_file") == 1 ]] ||
        fail "setup-shell added Fish to the shells file more than once"
    fi

    printf 'Installer bootstrap test passed\n'
  '';
}
